### ISSUE TITLE
fazer_testes_pytest_test_main.py

### ISSUE THREAD

**Issue by CarolinaSanches24** [CarolinaSanches24/Desafio-Testes#7]
https://learn.microsoft.com/pt-br/training/modules/test-python-with-pytest/

**Comment by SimoneBraghin** [comment]
Obs. Para o teste funcionar, alterar nome do arquivo <\C:\Users\User\OneDrive\RepositoriosGitHub\Desafio-Testes\introducao_testes\test_exercise.py>

Por algum motivo, o arquivo test_exercise.py da pasta introducao_testes gera conflito neste teste (pasta fazer_testes_pytest.

Fiz a inclusão dos códigos e, para validar o teste, alterei o nome do arquivo naquela pasta (desfiz a mudança do nome após o teste)
